=== brianv0/pipeline-web/org-srs-pipeline-web/tags/v1r4p1/src/web/schemas/1.1/pipeline.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="http://glast-ground.slac.stanford.edu/pipeline" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://glast-ground.slac.stanford.edu/pipeline" elementFormDefault="qualified" version="1.1">
   <xs:element name="pipeline">
      <xs:complexType>
         <xs:sequence>
            <xs:element name="name" type="TaskNameType"/>
            <xs:element name="type" type="TaskType"/>
            <xs:element name="notation" type="NotationType" minOccurs="0" maxOccurs="1"/>
            <xs:element name="dataset-base-path" type="BasePathType"/>
            <xs:element name="run-log-path" type="RunLogPathType"/>
            <xs:element ref="executable" maxOccurs="unbounded"/>
            <xs:element ref="batch-job-configuration" maxOccurs="unbounded"/>
            <xs:element ref="file" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element ref="foreign-input-file" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element ref="processing-step" maxOccurs="unbounded"/>
         </xs:sequence>
      </xs:complexType>
   </xs:element>
   <xs:simpleType name="TaskNameType">
      <xs:restriction base="xs:string">
         <xs:minLength value="1"/>
         <xs:maxLength value="30"/>
      </xs:restriction>
   </xs:simpleType>
   <xs:simpleType name="NotationType">
      <xs:restriction base="xs:string">
         <xs:minLength value="0"/>
         <xs:maxLength value="200"/>
      </xs:restriction>
   </xs:simpleType>
   <xs:simpleType name="TaskType">
      <xs:restriction base="xs:NMTOKEN">
         <xs:enumeration value="SimReconDigi"/>
         <xs:enumeration value="test"/>
         <xs:enumeration value="Analysis"/>
         <xs:enumeration value="Reconstruction"/>
         <xs:enumeration value="Digitization"/>
         <xs:enumeration value="Report"/>
         <xs:enumeration value="SystemTest"/>
         <xs:enumeration value="Simulation"/>
         <xs:enumeration value="Reprocessing"/>
         <xs:enumeration value="Conversion"/>
      </xs:restriction>
   </xs:simpleType>
   <xs:simpleType name="BasePathType">
      <xs:restriction base="xs:string">
         <xs:minLength value="0"/>
         <xs:maxLength value="200"/>
      </xs:restriction>
   </xs:simpleType>
   <xs:simpleType name="RunLogPathType">
      <xs:restriction base="xs:string">
         <xs:minLength value="1"/>
         <xs:maxLength value="200"/>
      </xs:restriction>
   </xs:simpleType>
	<!-- Application -->
   <xs:element name="executable" nillable="false">
      <xs:complexType>
         <xs:simpleContent>
            <xs:extension base="ExecutablePathType">
               <xs:attribute name="name" type="ExecutableNameType" use="required"/>
               <xs:attribute name="version" type="ExecutableVersionType" use="required"/>
            </xs:extension>
         </xs:simpleContent>
      </xs:complexType>
   </xs:element>
   <xs:simpleType name="ExecutablePathType">
      <xs:restriction base="xs:string">
         <xs:minLength value="1"/>
         <xs:maxLength value="200"/>
      </xs:restriction>
   </xs:simpleType>
   <xs:simpleType name="ExecutableNameType">
      <xs:restriction base="xs:string">
         <xs:minLength value="1"/>
         <xs:maxLength value="20"/>
      </xs:restriction>
   </xs:simpleType>
   <xs:simpleType name="ExecutableVersionType">
      <xs:restriction base="xs:string">
         <xs:minLength value="1"/>
         <xs:maxLength value="20"/>
      </xs:restriction>
   </xs:simpleType>
	<!-- JobConfiguration-->
   <xs:element name="batch-job-configuration">
      <xs:complexType>
         <xs:sequence>
            <xs:element name="working-directory" type="WorkingDirectoryType"/>
            <xs:element name="log-file-path" type="LogFilePathType"/>
         </xs:sequence>
         <xs:attribute name="name" type="xs:string" use="required"/>
         <xs:attribute name="queue" type="BatchQueue" use="required"/>
         <xs:attribute name="group" type="BatchGroup" use="required"/>
      </xs:complexType>
   </xs:element>
   <xs:simpleType name="WorkingDirectoryType">
      <xs:restriction base="xs:string">
         <xs:minLength value="0"/>
         <xs:maxLength value="200"/>
      </xs:restriction>
   </xs:simpleType>
   <xs:simpleType name="LogFilePathType">
      <xs:restriction base="xs:string">
         <xs:minLength value="1"/>
         <xs:maxLength value="200"/>
      </xs:restriction>
   </xs:simpleType>
   <xs:simpleType name="BatchQueue">
      <xs:restriction base="xs:NMTOKEN">
         <xs:enumeration value="ilcglastq"/>
         <xs:enumeration value="long"/>
         <xs:enumeration value="short"/>
         <xs:enumeration value="xlong"/>
         <xs:enumeration value="medium"/>
         <xs:enumeration value="xxl"/>
         <xs:enumeration value="express"/>
      </xs:restriction>
   </xs:simpleType>
   <xs:simpleType name="BatchGroup">
      <xs:restriction base="xs:NMTOKEN">
         <xs:enumeration value="none"/>
         <xs:enumeration value="glastgrp"/>
         <xs:enumeration value="glastdata"/>
      </xs:restriction>
   </xs:simpleType>
   <!-- Dataset -->
   <xs:element name="file">
      <xs:complexType>
          <xs:sequence>
            <xs:element name="notation" type="NotationType" minOccurs="0" maxOccurs="1"/>
            <xs:element name="path" type="PathType"/>
         </xs:sequence>
         <xs:attribute name="name" type="DatasetNameType" use="required"/>
         <xs:attribute name="type" type="DatasetType" use="required"/>
         <xs:attribute name="file-type" type="DatasetFileType" use="required"/>
      </xs:complexType>
   </xs:element>
   <xs:simpleType name="PathType">
      <xs:restriction base="xs:string">
         <xs:minLength value="1"/>
         <xs:maxLength value="200"/>
      </xs:restriction>
   </xs:simpleType>
   <xs:element name="foreign-input-file">
      <xs:complexType>
         <xs:simpleContent>
            <xs:extension base="xs:string">
               <xs:attribute name="name" type="DatasetNameType" use="required"/>
               <xs:attribute name="pipeline" type="TaskNameType" use="required"/>
               <xs:attribute name="file" type="DatasetNameType" use="required"/>
            </xs:extension>
         </xs:simpleContent>
      </xs:complexType>
   </xs:element>
   <xs:simpleType name="DatasetNameType">
      <xs:restriction base="xs:string">
         <xs:minLength value="1"/>
         <xs:maxLength value="30"/>
      </xs:restriction>
   </xs:simpleType>
   <xs:simpleType name="DatasetType">
      <xs:restriction base="xs:NMTOKEN">
         <xs:enumeration value="MC"/>
         <xs:enumeration value="Analysis"/>
         <xs:enumeration value="text"/>
         <xs:enumeration value="LDF"/>
         <xs:enumeration value="DIGI"/>
         <xs:enumeration value="RAW"/>
         <xs:enumeration value="rcReport"/>
         <xs:enumeration value="merit"/>
         <xs:enumeration value="svac"/>
         <xs:enumeration value="histogram"/>
         <xs:enumeration value="script"/>
         <xs:enumeration value="log"/>
         <xs:enumeration value="ntuple"/>
         <xs:enumeration value="tree"/>
         <xs:enumeration value="RECON"/>
      </xs:restriction>
   </xs:simpleType>
   <xs:simpleType name="DatasetFileType">
      <xs:restriction base="xs:NMTOKEN">
         <xs:enumeration value="jobOpt"/>
         <xs:enumeration value="root"/>
         <xs:enumeration value="txt"/>
         <xs:enumeration value="fits"/>
         <xs:enumeration value="pl"/>
         <xs:enumeration value="csh"/>
         <xs:enumeration value="tgz"/>
         <xs:enumeration value="xml"/>
         <xs:enumeration value="sh"/>
         <xs:enumeration value="tar"/>
         <xs:enumeration value="gz"/>
         <xs:enumeration value="tar.gz"/>
         <xs:enumeration value="pdf"/>
         <xs:enumeration value="ps"/>
         <xs:enumeration value="html"/>
         <xs:enumeration value="tex"/>
      </xs:restriction>
   </xs:simpleType>
   <xs:element name="processing-step">
      <xs:complexType>
         <xs:sequence>
            <xs:element name="notation" type="NotationType" minOccurs="0" maxOccurs="1"/>
            <xs:element name="input-file" minOccurs="0" maxOccurs="unbounded">
               <xs:complexType>
                  <xs:sequence>
                     <xs:element name="notation" type="NotationType" minOccurs="0" maxOccurs="1"/>
                  </xs:sequence>
                  <xs:attribute name="name" type="xs:string" use="required"/>
               </xs:complexType>
            </xs:element>
            <xs:element name="output-file" minOccurs="0" maxOccurs="unbounded">
               <xs:complexType>
                  <xs:sequence>
                     <xs:element name="notation" type="NotationType" minOccurs="0" maxOccurs="1"/>
                  </xs:sequence>
                  <xs:attribute name="name" type="xs:string" use="required"/>
               </xs:complexType>
            </xs:element>
         </xs:sequence>
         <xs:attribute name="name" type="xs:string" use="required"/>
         <xs:attribute name="executable" type="xs:string" use="required"/>
         <xs:attribute name="batch-job-configuration" type="xs:string" use="required"/>
      </xs:complexType>
   </xs:element>
</xs:schema>

=== brianv0/pipeline-web/org-srs-pipeline-web/tags/v2r6/src/web/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<pipeline
    xmlns="http://glast-ground.slac.stanford.edu/pipeline"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://glast-ground.slac.stanford.edu/pipeline http://glast-ground.slac.stanford.edu/Pipeline/schemas/1.1/pipeline.xsd">
    <name>interleaveDC2-GR-v7r3p21</name>
    <type>SimReconDigi</type>
    <notation>-</notation>
    <dataset-base-path>/nfs/farm/g/glast/u28/MC-tasks/interleaveDC2-GR-v7r3p21/output/$(RUN_NAME)/</dataset-base-path>
    <run-log-path>/temp</run-log-path>
        <executable name="mc1stepWrapper" version="dummy">
            /nfs/farm/g/glast/u28/MC-tasks/interleaveDC2-GR-v7r3p21/config/productionMonteCarlo.pl
        </executable>
        <batch-job-configuration group="glastgrp" name="long-job" queue="long">
            <working-directory>/nfs/farm/g/glast/u28/MC-tasks/interleaveDC2-GR-v7r3p21/output/$(RUN_NAME)</working-directory>
            <log-file-path>/nfs/farm/g/glast/u28/MC-tasks/interleaveDC2-GR-v7r3p21/output/$(RUN_NAME)</log-file-path>
        </batch-job-configuration>
        <file name="recon" type="RECON" file-type="root">
            <notation>-</notation>
            <path>/</path>
        </file>
        <file name="merit" type="merit" file-type="root">
            <notation>-</notation>
            <path>/</path>
        </file>
        <file name="digi" type="DIGI" file-type="root">
            <notation>-</notation>
            <path>/</path>
        </file>
        <file name="mc" type="MC" file-type="root">
            <notation>-</notation>
            <path>/</path>
        </file>
        <processing-step name="mc1step" executable="mc1stepWrapper" batch-job-configuration="long-job">
            <notation>-</notation>
                        <output-file name="merit"/>
                        <output-file name="mc"/>
                        <output-file name="digi"/>
                        <output-file name="recon"/>
        </processing-step>
</pipeline>
